# Main entrypoint of the workflow.
# Please follow the best practices:
# https://snakemake.readthedocs.io/en/stable/snakefiles/best_practices.html,
# in particular regarding the standardized folder structure mentioned there.


container: "docker://condaforge/miniforge3"


include: "rules/renv.smk"
include: "rules/quarto_examples.smk"
