---
repos:
    - hooks:
          - id: snakefmt
      repo: https://github.com/snakemake/snakefmt
      rev: v0.8.4
    - repo: https://github.com/astral-sh/ruff-pre-commit
      # Ruff version.
      rev: v0.1.7
      hooks:
          - id: ruff
            types_or: [python, pyi, jupyter]
            args: [--fix, --exit-non-zero-on-fix]
    - repo: https://github.com/asottile/reorder-python-imports
      rev: v3.12.0
      hooks:
          - id: reorder-python-imports
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0
      hooks:
          - id: check-added-large-files
          - id: check-yaml
          - id: check-toml
          - id: check-json
          - id: check-merge-conflict
          - id: check-added-large-files
          - id: end-of-file-fixer
            exclude: \.Rd # sometimes roxygen fails to generate EOF blank line.
          - id: file-contents-sorter
            files: ^\.Rbuildignore$
    - repo: https://github.com/psf/black
      rev: 23.12.0
      hooks:
          - id: black
            args: [--line-length, '88']
          - id: black-jupyter
    - repo: https://github.com/kynan/nbstripout
      rev: 0.6.1
      hooks:
          - id: nbstripout
            files: \.ipynb$
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v1.7.1  # Use the sha / tag you want to point at
      hooks:
          - id: mypy
            args: [--python-version=3.11, --ignore-missing-imports]
    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.2.3 # or other specific tag
      hooks:
          - id: yamlfmt
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v1.2.3
      hooks:
          - id: check-added-large-files
            args: [--maxkb=200]
          - id: end-of-file-fixer
            exclude: \.Rd
    - repo: https://github.com/pre-commit-ci/pre-commit-ci-config
      rev: v1.5.1
      hooks:
      # Only required when https://pre-commit.ci is used for config validation
          - id: check-pre-commit-ci-config
    - repo: local
      hooks:
          - id: forbid-to-commit
            name: Don't commit common R artifacts
            entry: Cannot commit .Rhistory, .RData, .Rds or .rds.
            language: fail
            files: \.(Rhistory|RData|Rds|rds)$
          # `exclude: <regex>` to allow committing specific files
